import json
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictInt,
    computed_field,
    field_validator,
    model_validator,
)
from typing import Annotated, Dict, Any, Literal, Optional
from datetime import datetime

from services.dataset_identity import SERVER_IDENTITY_FIELDS
from services.model_artifacts import is_valid_model_weight_file

PositiveId = Annotated[StrictInt, Field(gt=0)]


class TrainingTagResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    name: str


class TrainingTagNameRequest(BaseModel):
    name: str = Field(min_length=1, max_length=64)

    @field_validator("name", mode="before")
    @classmethod
    def trim_name(cls, value):
        return value.strip() if isinstance(value, str) else value


class ReplaceTrainingTaskTagsRequest(BaseModel):
    tag_ids: list[PositiveId]


class UpdateTrainingTaskTagsRequest(BaseModel):
    task_ids: list[PositiveId]
    tag_ids: list[PositiveId]
    operation: Literal["add", "remove"]

class TrainingStartRequest(BaseModel):
    model_script: str = Field(..., description="The script filename to execute")
    hyperparameters: Dict[str, Any] = Field(default_factory=dict, description="Custom hyperparameters")
    model_name: str = Field(..., min_length=1, description="Required unique name for the resulting model")
    data_source: str = Field(default="default", description="server-managed training dataset source")
    model_source: str = Field(default="official", description="official | uploaded")
    uploaded_model_id: Optional[str] = Field(default=None, description="Validated uploaded model package id")
    tag_ids: list[PositiveId] = Field(default_factory=list)
    dataset_id: Optional[str] = Field(
        default=None,
        description="Registered server dataset id; legacy hyperparameters.training_dataset also works",
    )

    @model_validator(mode="before")
    @classmethod
    def reject_client_dataset_identity(cls, value):
        # Only the top level dataset_id and the legacy training_dataset may be
        # sent. Version, fingerprint, status and snapshot are server generated.
        if isinstance(value, dict) and SERVER_IDENTITY_FIELDS.intersection(value):
            raise ValueError("Dataset identity is generated by the server")
        return value


class RenameTrainingModelRequest(BaseModel):
    model_name: str = Field(..., min_length=1, max_length=255)

class TrainingTaskResponse(BaseModel):
    id: int
    tags: list[TrainingTagResponse] = Field(default_factory=list)
    model_script: str
    model_source: str = "official"
    uploaded_model_id: Optional[str] = None
    uploaded_model_version: Optional[int] = None
    status: str
    start_time: datetime
    end_time: Optional[datetime]
    hyperparameters: str
    log_file_path: Optional[str]
    output_model_path: Optional[str]
    custom_model_name: Optional[str]
    metrics: Optional[str]
    progress: float
    current_epoch: int
    total_epochs: int
    current_loss: Optional[float]
    eta: Optional[str]
    loss_history: Optional[str]

    # Dataset identity. Old clients may ignore these fields; historical tasks
    # without a binding return null and never break the whole list.
    dataset_id: Optional[str] = None
    dataset_version: Optional[str] = None
    dataset_fingerprint: Optional[str] = None
    dataset_identity_status: Optional[str] = None
    dataset_snapshot: Optional[Dict[str, Any]] = None

    @field_validator("dataset_snapshot", mode="before")
    @classmethod
    def decode_dataset_snapshot(cls, value):
        if value is None or isinstance(value, dict):
            return value
        try:
            parsed = json.loads(value)
        except (TypeError, ValueError):
            return None
        return parsed if isinstance(parsed, dict) else None

    @computed_field(return_type=bool)
    @property
    def model_available(self) -> bool:
        return self.status == "completed" and is_valid_model_weight_file(self.output_model_path)

    class Config:
        from_attributes = True

class LogResponse(BaseModel):
    lines: list[str]


class TrainingWeightFileResponse(BaseModel):
    id: str
    user_id: int
    original_filename: str
    content_hash: str
    file_size: int
    status: str
    validation_report: Dict[str, Any] = Field(default_factory=dict)
    created_at: Optional[datetime] = None

    class Config:
        from_attributes = True


class TrainingWeightFileListResponse(BaseModel):
    items: list[TrainingWeightFileResponse]
